### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lschriml**
I would like to update the Gaz readme.
Cheers,
Lynn

### CODE REVIEW

**Comment by pbuttigieg** [comment]
Hi @lschriml, we've been using "lead editor " or "chief editor " in these projects lately. More technically accurate than PI and more clear to users. Can this be changed?

**Comment by lschriml** [comment]
Yes, I like that better, lead editor.

**Comment by lschriml** [comment]
Done on https://github.com/lschriml/gaz/blob/master/README.md

Can you make the change on the GAZ GitHub: 
https://github.com/EnvironmentOntology/gaz

Cheers,
Lynn

**Comment by pbuttigieg** [comment]
Hi @lschriml 
Merging this, but I'm not sure if your latest changes are there. Will fix if not.

**Comment by pbuttigieg** [comment]
The following section was not merged:

>GAZ in GitHub
GitHub can handle large files, with the extension: git-lfs [Download] (https://git-lfs.github.com)

I also don't see why we would merge it unless GAZ is actually hosted there. Is it?

**Pull request merged**
